### PR TITLE
Free convection neural PDE prototype

### PR DESCRIPTION
**Pull request by ali-ramadhan**
PR is still a work-in-progress.

Was able to train the neural network to reproduce the heat flux profiles from Oceananigans. Should see how much the `ConservativeFluxLayer` helps.

Neural PDE then time steps but needs to be trained. Lots more to do (+ code organization) but at least it doesn't `NaN` out super quickly.

free_convection_learned_heat_flux

free_convection_neural_pde

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
So wT is correct but the integration is still unstable?

**Comment by ChrisRackauckas** [comment]
Something looks up with the boundary condition at zero.

**Comment by ali-ramadhan** [comment]
> So wT is correct but the integration is still unstable?

Yes but not surprising as I still haven't trained the `NeuralODE`. Doing this now.

> Something looks up with the boundary condition at zero.

Yeah I was using a custom `ConservativeFluxLayer` that injects the correct boundary conditions at the top and bottom (since they're prescribed) via
```julia
(L::ConservativeFluxLayer)(ϕ, p...) = cat(L.bottom_flux, ϕ, L.top_flux, dims=1)
```
which worked when training wT via `Flux.train!` but errored out when training the `NeuralODE` via `DiffEqFlux.sciml_train`.

I think I just need to use it as a Flux layer when training with `Flux.train!` then convert it to a `FastLayer` when using `DiffEqFlux.sciml_train`.

**Comment by ali-ramadhan** [comment]
Doing better:

free_convection_neural_pde

**Comment by ali-ramadhan** [comment]
Switching to `ROCK4` and reducing to `reltol=1e-3` helped keep it stable for longer. Guess I should work on scaling it up to predict a longer time series. Also should figure out if I'm non-dimensionalizing the PDE correctly.

free_convection_neural_pde

**Comment by ali-ramadhan** [comment]
Looking much better after I non-dimensionalized the neural PDE properly:

free_convection_neural_pde

**Comment by ChrisRackauckas** [comment]
Have you tried swapping the NN for a Legendre basis?

**Comment by ali-ramadhan** [comment]
Not yet, that was partly the reason for #5, didn't realize you could use `TensorLayer` for that! Will look into switching to a Legendre basis, which should be super nice as the surrogate model would then be resolution independent.

**Pull request merged**
